version: "3"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "11001:80"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://admin:admin@host.docker.internal:11002/sample

  db:
    image: postgres
    ports:
      - "11002:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sample
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
